<a href="https://colab.research.google.com/github/zoroubo/MDS-lab/blob/main/week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
import time


In [ ]:
size = 1000000

# Python List
python_list_a = list(range(size))
python_list_b = list(range(size))

start_time = time.time()
python_result = [a + b for a, b in zip(python_list_a, python_list_b)]
end_time = time.time()
python_list_time = end_time - start_time
print(f"Time taken for Python List operation: {python_list_time:.6f} seconds")

# NumPy Array
numpy_array_a = np.arange(size)
numpy_array_b = np.arange(size)

start_time = time.time()
numpy_result = numpy_array_a + numpy_array_b
end_time = time.time()
numpy_array_time = end_time - start_time
print(f"Time taken for NumPy Array operation: {numpy_array_time:.6f} seconds")

print(f"\nNumPy array was {python_list_time / numpy_array_time:.2f} times faster than Python list.")

Time taken for Python List operation: 0.077123 seconds
Time taken for NumPy Array operation: 0.004781 seconds

NumPy array was 16.13 times faster than Python list.


In [ ]:
import sys

# Assuming 'size' is already defined from the previous cell (1,000,000)
# If not, uncomment the line below:
# size = 1000000

# Python List memory usage
python_list = list(range(size))
python_list_memory = sys.getsizeof(python_list) # Size of the list object itself
# To get a more accurate total memory, we'd also need to sum the size of each element.
# However, for comparison, the object size and knowing elements are separate is sufficient.
# For simple integers, it's often 28 bytes per int on 64-bit systems + list overhead.
python_list_elements_memory = sum(sys.getsizeof(0) for _ in range(size)) # Approximation for int elements

print(f"Python List (object itself) memory: {python_list_memory / (1024*1024):.4f} MB")
print(f"Python List (approx. total with elements) memory: {(python_list_memory + python_list_elements_memory) / (1024*1024):.4f} MB")

# NumPy Array memory usage
numpy_array = np.arange(size)
numpy_array_memory = numpy_array.nbytes # Total bytes consumed by the array data

print(f"NumPy Array memory: {numpy_array_memory / (1024*1024):.4f} MB")

print(f"\nObservation: NumPy arrays are significantly more memory-efficient for numerical data.")

Python List (object itself) memory: 7.6294 MB
Python List (approx. total with elements) memory: 34.3323 MB
NumPy Array memory: 7.6294 MB

Observation: NumPy arrays are significantly more memory-efficient for numerical data.


In [ ]:
import numpy as np

# 1. From a Python List
list_data = [1, 2, 3, 4, 5]
arr_from_list = np.array(list_data)
print(f"From List: {arr_from_list}, Type: {type(arr_from_list)}")

# 2. From a Python Tuple
tuple_data = (6, 7, 8, 9, 10)
arr_from_tuple = np.array(tuple_data)
print(f"From Tuple: {arr_from_tuple}, Type: {type(arr_from_tuple)}")

# 3. From a nested Python List (to create a 2D array)
nested_list_data = [[1, 2, 3], [4, 5, 6]]
arr_2d_from_list = np.array(nested_list_data)
print(f"From Nested List (2D):\n{arr_2d_from_list}, Shape: {arr_2d_from_list.shape}")

# 4. From a Python Dictionary (common approach: convert values or items to list first)
dict_data = {'a': 1, 'b': 2, 'c': 3}
# To create an array of dictionary values:
arr_from_dict_values = np.array(list(dict_data.values()))
print(f"From Dictionary Values: {arr_from_dict_values}")

# To create an array of dictionary items (key-value pairs as tuples, then converted):
arr_from_dict_items = np.array(list(dict_data.items()), dtype=object) # dtype=object might be needed for mixed types
print(f"From Dictionary Items (array of tuples):\n{arr_from_dict_items}")

# 5. From an iterable (e.g., a generator)
gen_data = (x*x for x in range(5))
arr_from_gen = np.array(list(gen_data)) # Convert generator to list first
print(f"From Generator: {arr_from_gen}")

From List: [1 2 3 4 5], Type: <class 'numpy.ndarray'>
From Tuple: [ 6  7  8  9 10], Type: <class 'numpy.ndarray'>
From Nested List (2D):
[[1 2 3]
 [4 5 6]], Shape: (2, 3)
From Dictionary Values: [1 2 3]
From Dictionary Items (array of tuples):
[['a' 1]
 ['b' 2]
 ['c' 3]]
From Generator: [ 0  1  4  9 16]


In [ ]:
l=['a','g']
x=np.array(l)
print(x.dtype) # Corrected to access the dtype attribute of the array
x.shape


<U1


(2,)

In [ ]:
import numpy as np

t = (6, 7, 8, 9, 10)
l1 = [1, 2, 3, 4, 5] # Corrected syntax for list l1

# Create a 2D array from l1
array_1d = np.array(l1)
array_2d = array_1d.reshape(1, -1) # Reshape to a 2D array with 1 row and inferred columns

print(f"Original list l1: {l1}")
print(f"1D NumPy array from l1: {array_1d}")
print(f"Shape of 1D array: {array_1d.shape}")
print(f"2D NumPy array from l1:\n{array_2d}")
print(f"Shape of 2D array: {array_2d.shape}")

Original list l1: [1, 2, 3, 4, 5]
1D NumPy array from l1: [1 2 3 4 5]
Shape of 1D array: (5,)
2D NumPy array from l1:
[[1 2 3 4 5]]
Shape of 2D array: (1, 5)


In [ ]:
l2=[[1,2],[3,4],[5,6]]
type(l2)
arr1=np.array(l2)
print(arr1)
print(arr1.ndim)
arr1.size

[[1 2]
 [3 4]
 [5 6]]
2


6

In [ ]:
a=np.arange(0,100,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [ ]:
y=np.array([1.8,2,3,4],dtype=np.float64)
print(y)
x=y.astype(str)
print(x)


[1.8 2.  3.  4. ]
['1.8' '2.0' '3.0' '4.0']


In [ ]:
import numpy as np

# Create a 4D matrix with only zeros
zeros_4d_matrix = np.zeros((2, 3, 4, 5))
print("4D Matrix with Zeros:\n", zeros_4d_matrix)
print("Shape of zeros_4d_matrix:", zeros_4d_matrix.shape)
print("---------------------------------------------------")

# Create a 4D matrix with only ones
ones_4d_matrix = np.ones((2, 3, 4, 5))
print("4D Matrix with Ones:\n", ones_4d_matrix)
print("Shape of ones_4d_matrix:", ones_4d_matrix.shape)

4D Matrix with Zeros:
 [[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
Shape of zeros_4d_matrix: (2, 3, 4, 5)
---------------------------------------------------
4D Matrix with Ones:
 [[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]

In [ ]:
import numpy as np

print("### NumPy Random Functions ###")

# np.random.rand() - Uniform random numbers between 0 and 1
# Useful for probabilities or simple random values.
print("\n--- np.random.rand --- ")
print(np.random.rand(3, 2)) # A 3x2 array of random floats

# np.random.randn() - Standard Normal (Gaussian) distribution (mean=0, variance=1)
# Useful for adding noise or sampling from a normal distribution.
print("\n--- np.random.randn --- ")
print(np.random.randn(4)) # 4 random floats from a standard normal distribution

# np.random.randint(low, high, size) - Random integers
# Useful for simulations like dice rolls or picking random indices.
print("\n--- np.random.randint --- ")
print(np.random.randint(1, 10, size=(2, 5))) # A 2x5 array of integers between 1 (inclusive) and 10 (exclusive)

# np.random.choice(array, size, replace=True/False) - Randomly select elements
# Useful for sampling data.
print("\n--- np.random.choice --- ")
my_list = ['A', 'B', 'C', 'D', 'E']
print(np.random.choice(my_list, size=3, replace=False)) # Choose 3 unique elements

# np.random.permutation(array or int) - Randomly reorder sequence
# Useful for shuffling datasets.
print("\n--- np.random.permutation --- ")
print(np.random.permutation(np.arange(5))) # Shuffles numbers 0 to 4

### NumPy Random Functions ###

--- np.random.rand --- 
[[0.47729981 0.95689657]
 [0.98423107 0.03894148]
 [0.06117845 0.1789703 ]]

--- np.random.randn --- 
[-0.03604252 -1.02783603 -0.5896397  -0.14466593]

--- np.random.randint --- 
[[6 4 8 1 6]
 [1 4 2 9 5]]

--- np.random.choice --- 
['C' 'D' 'A']

--- np.random.permutation --- 
[4 2 1 3 0]


In [ ]:

mat=np.arange(0,20).reshape(4,5)
print(mat.reshape(2,2,5))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
