<a href="https://colab.research.google.com/github/zoroubo/MDS-lab/blob/main/WEEK1-2.0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr_1d = np.array([52, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Original 1D array: {arr_1d}")

# Slice from index 2 up to (but not including) index 7
sliced_arr = arr_1d[2:7]
print(f"arr_1d[2:7]: {sliced_arr}")

# Slice from the beginning up to index 5
sliced_arr_start = arr_1d[:5]
print(f"arr_1d[:5]: {sliced_arr_start}")

# Slice from index 4 to the end
sliced_arr_end = arr_1d[4:]
print(f"arr_1d[4:]: {sliced_arr_end}")

# Slice the entire array
sliced_arr_all = arr_1d[:]
print(f"arr_1d[:]: {sliced_arr_all}")

Original 1D array: [0 1 2 3 4 5 6 7 8 9]
arr_1d[2:7]: [2 3 4 5 6]
arr_1d[:5]: [0 1 2 3 4]
arr_1d[4:]: [4 5 6 7 8 9]
arr_1d[:]: [0 1 2 3 4 5 6 7 8 9]


In [12]:
print(f"Original 1D array: {arr_1d}")

# Slice every second element
stepped_arr = arr_1d[::2]
print(f"arr_1d[::2]: {stepped_arr}")

# Slice from index 1 to 8, taking every third element
stepped_arr_range = arr_1d[1:9:3]
print(f"arr_1d[1:9:3]: {stepped_arr_range}")

# Reverse the array
reversed_arr = arr_1d[::-1]
print(f"arr_1d[::-1]: {reversed_arr}")

Original 1D array: [0 1 2 3 4 5 6 7 8 9]
arr_1d[::2]: [0 2 4 6 8]
arr_1d[1:9:3]: [1 4 7]
arr_1d[::-1]: [9 8 7 6 5 4 3 2 1 0]


In [14]:
arr_2d = np.array([
    [52, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
print("Original 2D array:\n", arr_2d)

# Select rows from index 0 to 1, and all columns
slice_rows = arr_2d[0:2, :]
print(f"\narr_2d[0:2, :]:\n{slice_rows}")

# Select all rows, and columns from index 1 to 3
slice_cols = arr_2d[:, 1:4]
print(f"\narr_2d[:, 1:4]:\n{slice_cols}")

# Select rows from index 1 to 2, and columns from index 0 to 1
slice_submatrix = arr_2d[1:3, 0:2]
print(f"\narr_2d[1:3, 0:2]:\n{slice_submatrix}")

# Select a single row (index 2)
single_row = arr_2d[2, :]
print(f"\narr_2d[2, :]: {single_row}")

# Select a single column (index 1)
single_col = arr_2d[:, 1]
print(f"\narr_2d[:, 1]: {single_col}")

Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

arr_2d[0:2, :]:
[[1 2 3 4]
 [5 6 7 8]]

arr_2d[:, 1:4]:
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]

arr_2d[1:3, 0:2]:
[[ 5  6]
 [ 9 10]]

arr_2d[2, :]: [ 9 10 11 12]

arr_2d[:, 1]: [ 2  6 10 14]


In [15]:
arr_bool = np.array([52, 20, 30, 40, 50, 60])
print(f"Original array: {arr_bool}")

# Select elements greater than 30
condition = arr_bool > 30
print(f"Condition (arr_bool > 30): {condition}")
selected_elements = arr_bool[condition]
print(f"Elements > 30: {selected_elements}")

# Select elements that are even
even_elements = arr_bool[arr_bool % 2 == 0]
print(f"Even elements: {even_elements}")

Original array: [10 20 30 40 50 60]
Condition (arr_bool > 30): [False False False  True  True  True]
Elements > 30: [40 50 60]
Even elements: [10 20 30 40 50 60]


In [20]:
arr_fancy = np.array([52, 101, 102, 103, 104, 105])
print(f"Original array: {arr_fancy}")

# Select elements at specific indices
indices = np.array([0, 3, 5])
selected_fancy = arr_fancy[indices]
print(f"Elements at indices [0, 3, 5]: {selected_fancy}")

# Select rows from a 2D array using integer array indexing
print("\nOriginal 2D array:\n", arr_2d)
rows_to_select = np.array([0, 3, 1])
selected_2d_rows = arr_2d[rows_to_select]
print(f"\nSelected rows using indices [0, 3, 1]:\n{selected_2d_rows}")

# Select specific elements using a 2D integer array (one for rows, one for columns)
# This picks (arr_2d[0, 0]), (arr_2d[1, 2]), (arr_2d[3, 1])
row_indices = np.array([0, 1, 3])
col_indices = np.array([0, 2, 1])
selected_individual_elements = arr_2d[row_indices, col_indices]
print(f"\nSelected individual elements using (row_indices, col_indices): {selected_individual_elements}")

Original array: [100 101 102 103 104 105]
Elements at indices [0, 3, 5]: [100 103 105]

Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Selected rows using indices [0, 3, 1]:
[[ 1  2  3  4]
 [13 14 15 16]
 [ 5  6  7  8]]

Selected individual elements using (row_indices, col_indices): [ 1  7 14]


Original 1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped to 3x4 2D array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)

Reshaped to 4x3 2D array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)

Reshaped to 2x2x3 3D array:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Shape: (2, 2, 3)

Reshaped to 4x-1 2D array (inferred cols):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)

Reshaped to -1x6 2D array (inferred rows):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Shape: (2, 6)



In [55]:
import numpy as np

# Create a 1D array
arr = np.arange(12)
print(f"Original 1D array:\n{arr}\nShape: {arr.shape}\n")

# Reshape to a 2D array (3 rows, 4 columns)
arr_2d = arr.reshape(3, 4)
print(f"Reshaped to 3x4 2D array:\n{arr_2d}\nShape: {arr_2d.shape}\n")

# Reshape to another 2D array (4 rows, 3 columns)
arr_2d_another = arr.reshape(4, 3)
print(f"Reshaped to 4x3 2D array:\n{arr_2d_another}\nShape: {arr_2d_another.shape}\n")

# Reshape to a 3D array (2 'layers', 2 rows, 3 columns)
arr_3d = arr.reshape(2, 2, 3)
print(f"Reshaped to 2x2x3 3D array:\n{arr_3d}\nShape: {arr_3d.shape}\n")

# Using -1 to infer one dimension
# Reshape to 2D array, inferring the number of columns
arr_inferred_cols = arr.reshape(4, -1)
print(f"Reshaped to 4x-1 2D array (inferred cols):\n{arr_inferred_cols}\nShape: {arr_inferred_cols.shape}\n")

# Reshape to 2D array, inferring the number of rows
arr_inferred_rows = arr.reshape(-1, 6)
print(f"Reshaped to -1x6 2D array (inferred rows):\n{arr_inferred_rows}\nShape: {arr_inferred_rows.shape}\n")
# Flatten the 3D array arr_3d back to a 1D array
flattened_arr = arr_3d.flatten()
print(f"Original 3D array:\n{arr_3d}\n")
print(f"Flattened 1D array:\n{flattened_arr}\nShape: {flattened_arr.shape}")


Original 1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped to 3x4 2D array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)

Reshaped to 4x3 2D array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)

Reshaped to 2x2x3 3D array:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Shape: (2, 2, 3)

Reshaped to 4x-1 2D array (inferred cols):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)

Reshaped to -1x6 2D array (inferred rows):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Shape: (2, 6)

Original 3D array:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Flattened 1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)


In [57]:
import numpy as np

# --- Joining Arrays ---
print("--- Joining Arrays ---")

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# np.concatenate for 1D arrays
joined_1d = np.concatenate((arr1, arr2))
print(f"\nConcatenated 1D arrays: {joined_1d}")

arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])

# np.concatenate along axis 0 (rows)
joined_rows = np.concatenate((arr_a, arr_b), axis=0)
print(f"\nConcatenated along axis 0 (rows):\n{joined_rows}")

# np.concatenate along axis 1 (columns)
joined_cols = np.concatenate((arr_a, arr_b), axis=1)
print(f"\nConcatenated along axis 1 (columns):\n{joined_cols}")

# np.vstack (vertical stack) - stacks arrays row-wise
v_stacked = np.vstack((arr_a, arr_b))
print(f"\nVertically stacked (vstack):\n{v_stacked}")

# np.hstack (horizontal stack) - stacks arrays column-wise
h_stacked = np.hstack((arr_a, arr_b))
print(f"\nHorizontally stacked (hstack):\n{h_stacked}")



--- Joining Arrays ---

Concatenated 1D arrays: [1 2 3 4 5 6]

Concatenated along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1 (columns):
[[1 2 5 6]
 [3 4 7 8]]

Vertically stacked (vstack):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally stacked (hstack):
[[1 2 5 6]
 [3 4 7 8]]


In [59]:
# --- Splitting Arrays ---
print("\n--- Splitting Arrays ---")

# Splitting a 1D array
arr_1d_split = arr_1d # Reusing arr_1d from previous cells
print(f"Original 1D array for splitting: {arr_1d_split}")

# Split into 2 equal parts
split_1d_equal = np.split(arr_1d_split, 2)
print(f"Split into 2 equal parts: {split_1d_equal}")

# Split at specific indices
split_1d_indices = np.split(arr_1d_split, [3, 7])
print(f"Split at indices [3, 7]: {split_1d_indices}")

# Splitting a 2D array
arr_2d_split = np.arange(16).reshape(4, 4)
print(f"\nOriginal 2D array for splitting:\n{arr_2d_split}")

# np.vsplit (vertical split) - splits into equal rows
v_split = np.vsplit(arr_2d_split, 2)
print(f"\nVertically split into 2 parts (vsplit):\nPart 1:\n{v_split[0]}\nPart 2:\n{v_split[1]}")

# np.hsplit (horizontal split) - splits into equal columns
h_split = np.hsplit(arr_2d_split, 2)
print(f"\nHorizontally split into 2 parts (hsplit):\nPart 1:\n{h_split[0]}\nPart 2:\n{h_split[1]}")

# np.split on 2D array along axis 0 (rows)
split_2d_rows = np.split(arr_2d_split, 2, axis=0)
print(f"\nSplit along axis 0 (rows) into 2 parts:\nPart 1:\n{split_2d_rows[0]}\nPart 2:\n{split_2d_rows[1]}")

# np.split on 2D array along axis 1 (columns)
split_2d_cols = np.split(arr_2d_split, 2, axis=1)
print(f"\nSplit along axis 1 (columns) into 2 parts:\nPart 1:\n{split_2d_cols[0]}\nPart 2:\n{split_2d_cols[1]}")

# Using np.array_split for unequal splits
arr_uneven_split = arr[:11] # Reusing 'arr' and slicing it to get 11 elements
print(f"\nOriginal array for uneven splitting: {arr_uneven_split}")
uneven_split = np.array_split(arr_uneven_split, 3)
print(f"Uneven split into 3 parts: {uneven_split}")


--- Splitting Arrays ---
Original 1D array for splitting: [0 1 2 3 4 5 6 7 8 9]
Split into 2 equal parts: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
Split at indices [3, 7]: [array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

Original 2D array for splitting:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Vertically split into 2 parts (vsplit):
Part 1:
[[0 1 2 3]
 [4 5 6 7]]
Part 2:
[[ 8  9 10 11]
 [12 13 14 15]]

Horizontally split into 2 parts (hsplit):
Part 1:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Part 2:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

Split along axis 0 (rows) into 2 parts:
Part 1:
[[0 1 2 3]
 [4 5 6 7]]
Part 2:
[[ 8  9 10 11]
 [12 13 14 15]]

Split along axis 1 (columns) into 2 parts:
Part 1:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Part 2:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

Original array for uneven splitting: [ 0  1  2  3  4  5  6  7  8  9 10]
Uneven split into 3 parts: [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]
